version: '2'
services:
  web:
       build:
               context: ./
               dockerfile: Dockerfile
       container_name: hello_app
       image: helloimage:rahul
       volumes:
          - ./src:/var/www/html/
       ports:
         - 8085:80
 
